### PR TITLE
Support overriding ranlib on macOS with env var

### PR DESCRIPTION
**Pull request by isuruf**
Previously opened by mistake in https://github.com/pypa/setuptools/pull/2754

Fixes https://bugs.python.org/issue37916

### CODE REVIEW

**Comment by isuruf** [comment]
Can someone approve for github actions to start?

**Comment by isuruf** [comment]
Thanks. I pushed again. Needs approval

**Comment by isuruf** [comment]
Tests pass on github actions in my fork. Ready for review.

**Review by FFY00 — APPROVED** [review]
This looks correct to me.

**Comment by isuruf** [comment]
Thanks @FFY00

**Pull request merged**
