### PR TITLE
Add clang mingw support

### PR DESCRIPTION
**Pull request by longnguyen2004**
Modified the `CygwinCCompiler` class to get the compiler from the `CC` and `CXX` environment variables, and delegating to a generic `gcc` if undefined. Should allow people to specify the compiler to be used.

### CODE REVIEW

**Comment by jaraco** [comment]
Running tests with this patch, I encounter an error:

```
distutils main $ tox
python installed: attrs==20.3.0,iniconfig==1.1.1,packaging==20.9,pluggy==0.13.1,py==1.10.0,pyparsing==2.4.7,pytest==6.2.3,toml==0.10.2
python run-test-pre: PYTHONHASHSEED='2896714691'
python run-test: commands[0] | pytest
====================================================================== test session starts ======================================================================
platform darwin -- Python 3.9.2, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
cachedir: .tox/python/.pytest_cache
rootdir: /Users/jaraco/code/public/pypa/distutils, configfile: pytest.ini
collected 288 items / 2 errors / 286 selected                                                                                                                   

============================================================================ ERRORS =============================================================================
___________________________________________________ ERROR collecting distutils/tests/test_cygwinccompiler.py ____________________________________________________
distutils/tests/test_cygwinccompiler.py:9: in <module>
    from distutils.cygwinccompiler import (check_config_h,
E   ImportError: cannot import name 'get_versions' from 'distutils.cygwinccompiler' (/Users/jaraco/code/public/pypa/distutils/distutils/cygwinccompiler.py)
___________________________________________________ ERROR collecting distutils/tests/test_cygwinccompiler.py ____________________________________________________
ImportError while importing test module '/Users/jaraco/code/public/pypa/distutils/distutils/tests/test_cygwinccompiler.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
distutils/tests/test_cygwinccompiler.py:9: in <module>
    from distutils.cygwinccompiler import (check_config_h,
E   ImportError: cannot import name 'get_versions' from 'distutils.cygwinccompiler' (/Users/jaraco/code/public/pypa/distutils/distutils/cygwinccompiler.py)
==================================================================== short test summary info ====================================================================
ERROR distutils/tests/test_cygwinccompiler.py - ImportError: cannot import name 'get_versions' from 'distutils.cygwinccompiler' (/Users/jaraco/code/public/pyp...
ERROR distutils/tests/test_cygwinccompiler.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
======================================================================= 2 errors in 0.58s =======================================================================
ERROR: InvocationError for command /Users/jaraco/code/public/pypa/distutils/.tox/python/bin/pytest (exited with code 2)
____________________________________________________________________________ summary ____________________________________________________________________________
ERROR:   python: commands failed

```

Sorry the repo doesn't yet offer CI. I likely need to get that set up.

**Comment by jaraco** [comment]
CI is now enabled on the main branch. Please merge or rebase to include the changes in this PR.

**Comment by longnguyen2004** [comment]
Thanks, however I need to be approved to run CI, please see the link here https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks

**Comment by longnguyen2004** [comment]
What's the status on this PR?

**Comment by jaraco** [comment]
LGTM. Tests are now passing.

**Pull request merged**
