### PR TITLE
Do not set rpath on windows

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by isuruf** [comment]
There's no test currently for cygwinccompiler. Not sure how to add them.

**Comment by isuruf** [comment]
ping on this

**Comment by jaraco** [comment]
Can you say a little bit more about what motivated you to make this change? Did you encounter an error? How is it that this issue is only relevant now, 21 years after the module was created?

**Comment by isuruf** [comment]
Projects supporting windows would always have a if condition to fix this, for eg:
https://github.com/h5py/h5py/blob/master/setup_build.py#L107-L108
https://github.com/msys2/MINGW-packages/blob/707dc76b8c2a11c6e896f72999efcfe68c7e1054/mingw-w64-gobject-introspection/0028-no-rpath-on-nt.patch#L8

MinGW patches python to remove rpath to make it easier to port projects
https://github.com/msys2/MINGW-packages/blob/2a99c1fe8b5c24f69585bc4836ddfaadca6c2891/mingw-w64-python/0085-distutils-compiler-enable-new-dtags.patch#L27-L29

Also see this setuptools issue,
https://github.com/pypa/setuptools/issues/2753

**Comment by isuruf** [comment]
Nvm,  I need to add it to msvc compiler. Not cygwin.

**Comment by isuruf** [comment]
Sorry about the noise

**Comment by mkoeppe** [comment]
We do see a related failure in SageMath on Cygwin when using `SETUPTOOLS_USE_DISTUTILS=local`. 
https://trac.sagemath.org/ticket/32944

PR https://github.com/pypa/setuptools/pull/2909 adds a CI for Cygwin, but it does not expose this failure because apparently linking is not actually tested

**Pull request closed without merging**
