### PR TITLE
bpo-41282: Load install schemes from sysconfig (port from CPython)

### PR DESCRIPTION
**Pull request by henryiii**
In response to https://github.com/pypa/setuptools/issues/2946.

Directly applying the changes from https://github.com/python/cpython/pull/24549. No other testing at the moment.

### CODE REVIEW

**Comment by henryiii** [comment]
Okay, guessing we will need pypy and pypy_nt added (@mattip, correct?). Also, "headers" is not present, but why isn't it triggering on "include"? That error (on 3.6) is weird. @frenzymadness, perhaps?

Also, shouldn't any PR to distutils in CPython automatically be requested to make a PR here?

**Comment by mattip** [comment]
Yes, PyPy 3.7 still needs `pypy` and `pypy_nt`. PyPy 3.8+ no longer does, we changed to the cpython layout schema (still using `implementation` and `implementation_lower` though).

**Comment by jaraco** [comment]
> Also, shouldn't any PR to distutils in CPython automatically be requested to make a PR here?

Yes, probably. I wasn't fully grasping the implications of the changes to CPython when I reviewed it. My (incorrect) assessment was that the changes to stdlib were primarily removing functionality toward deprecation and that this project could adopt those changes as needed/desired. I agree, changes to CPython should be ported here.

**Comment by jaraco** [comment]
Now I worry I may really have confused things with my analysis in pypa/setuptools#2946.

A few things:

- distutils has already adopted a _different_ technique for giving sysconfig primacy for install schemes (#23 and others).
- In that effort, I've identified that `headers` and `include` are not compatible, which is why `distutils` here still uses include.
- The PR that's most relevant to the issue is python/cpython#23142. That's the one where `_init_posix` was removed.

**Comment by jaraco** [comment]
Apologies for the bad advice on the relevant PR, but distutils has diverged from cpython/distutils in this effort, so I'm going to close.

**Pull request closed without merging**
