### PR TITLE
Add DIST_EXTRA_CONFIG option for passing setup.cfg overrides during build

### PR DESCRIPTION
**Pull request by zooba**
As discussed during https://github.com/pypa/cibuildwheel/pull/1144

### CODE REVIEW

**Comment by zooba** [comment]
Haven't done all my own testing yet - wanted to get the change up for discussion first.

**Comment by zooba** [comment]
I have now tested this as part of the cibuildwheel tests (thanks to `simpleindex` :-) )

**Comment by zooba** [comment]
@jaraco This is what we started discussing in https://github.com/pypa/cibuildwheel/pull/1144

**Comment by zooba** [comment]
@jaraco Ping again.

**Comment by jaraco** [comment]
I decided to go with `DIST_EXTRA_CONFIG` to decouple from the implementation.

**Comment by jaraco** [comment]
This change is [going out with Setuptools 65.4.0](https://github.com/pypa/setuptools/actions/runs/3119471228), slated to be on PyPI soon. Please take a look.

**Pull request merged**
