### PR TITLE
#219 Use sysconfig.get_config_h_filename() to locate pyconfig.h

### LINKED ISSUE #219: _get_python_inc_nt should use sysconfig.get_config_h_filename()
In Python 3.13, we're moving the location of `pyconfig.h` on Windows (in order to support free threaded builds, it now has to be generated/updated at build time, so it can't be static).

To correctly find the file location, we should call `sysconfig.get_config_h_filename()` rather than assuming it'll be in the `PC\` directory.

### PR DESCRIPTION
**Pull request by zooba**
I've used the minimal change here. It would be totally valid to always make this call and only add the path if it differs from `{prefix}\include`, but it still only affects the case where we're in a CPython build directory so I don't see any reason to touch code outside of the checks for that.

Fixes #219

### CODE REVIEW

**Comment by zooba** [comment]
Those failures seem to be due to `setuptools` not being installed by default in 3.12. I'd suggest that may indicate that earlier versions are testing the wrong distutils/setuptools versions, or at least missing the opportunity to test with the current code.

The tests impacted by this change passed. It's unfortunate that it aborts the parallel jobs so we can't see their results.

**Comment by lazka** [comment]
lgtm, but there is one more place where the old path is used: https://github.com/pypa/distutils/blob/35069adc37879439205b89165695af62da6edb16/distutils/sysconfig.py#L362-L371

**Comment by lazka** [comment]
> The tests impacted by this change passed. It's unfortunate that it aborts the parallel jobs so we can't see their results.

I've created #222 for this

**Comment by zooba** [comment]
> there is one more place where the old path is used

Is there any reason why this shouldn't just call `sysconfig` all the time? (Or just import the function from sysconfig instead of redefining it?)

**Comment by lazka** [comment]
lgtm

**Review by FFY00 — APPROVED** [review]

**Comment by zooba** [comment]
Ping on this issue.

**Comment by zooba** [comment]
Thanks Jason!

**Pull request merged**
