### PR TITLE
Fix PyPy3.8 install locations

### PR DESCRIPTION
**Pull request by isuruf**
Fixes https://github.com/pypa/distutils/issues/56

cc @mattip

### CODE REVIEW

**Comment by jaraco** [comment]
I'm reluctant to accept this change because the INSTALL_SCHEMES is a compatibility feature that's intended to be replaced by a mechanism whereby `sysconfig` will define the install schemes (and thus can be overridden by the interpreter build). I'd be okay with this change as a stop-gap as long as a long-term solution is also in place (or at least acknowledged in the requirements for a long-term solution).

**Comment by isuruf** [comment]
Even if so, not merging this would break PyPy3.8 with `SETUPTOOLS_USE_DISTUTILS=local`
which we don't want. I can use `sysconfig.get_paths` to populate `INSTALL_SCHEMES` here.

I agree that duplicating these with `sysconfig` and `distutils` is error prone, but `sysconfig`
is not as flexible as distutils. (For eg: userbase is configurable in distutils, but can only be changed
using an env var in sysconfig.)

**Comment by mattip** [comment]
I agree with @isuruf, this would be good to put in as a stop-gap. #23 seems to be a longer-term solution.

**Comment by mattip** [comment]
ping?

**Pull request merged**
